In [1]:
import torch 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

1.13.1+cu117


## Introduction to Tensors

### Creating a tensor

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as Python int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
# number of pairs of square brackets
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# Matrix
MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

In [14]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

Why random tensors? 

Random tensors are important, becasue the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

` Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers `


In [15]:
# Random tensors
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4173, 0.1236, 0.9729, 0.3175],
        [0.7848, 0.0277, 0.4851, 0.6789],
        [0.3791, 0.8639, 0.6846, 0.9365]])

In [16]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor.shape, random_image_size_tensor.ndim



(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [17]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [19]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [20]:
# Use torch.range()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [22]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=None,           # what datatype is the tensor (e.g. float32 or float64)
                               device=None,          # What device is your tensor on
                               requires_grad=False)  # whether or not to track gradients with this tensors operations

float_32_tensor

tensor([3., 6., 9.])

In [23]:
float_32_tensor.dtype

torch.float32

In [24]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [25]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [26]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [27]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [28]:
# Create a tensor
some_tensor = torch.rand(3,4)
print(some_tensor)
# Find out details
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.8030, 0.7072, 0.1767, 0.0911],
        [0.2349, 0.5745, 0.9875, 0.3652],
        [0.9716, 0.8840, 0.5823, 0.3839]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [33]:
# Create a tensor
tensor = torch.tensor([1,2,3])
# addition
print(f"addition: {tensor + 10}")
# multiplication
print(f"multiplication: {tensor * 10}")
# substraction
print(f"substraction: {tensor - 10}")
# pytorch in-built functions
print(f"in-built function: {torch.mul(tensor, 10)}")


addition: tensor([11, 12, 13])
multiplication: tensor([10, 20, 30])
substraction: tensor([-9, -8, -7])
in-built function: tensor([10, 20, 30])


### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix mutliplication (dot product)

There are two main rules that performing matrix mutliplication needs to satisfy:
1. The __inner dimensions__ must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work
2. The resulting matrix has the shape of the __outer dimensions__:
* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`

In [38]:
# Element wise multiplication
print(f"{tensor} * {tensor} equals: {tensor * tensor}")

# Matrix multiplication
print(f"Matrix multiplication: {torch.matmul(tensor, tensor)}")

tensor([1, 2, 3]) * tensor([1, 2, 3]) equals: tensor([1, 4, 9])
Matrix multiplication: 14


### Common errors: Shape errors

In [49]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print(f"Output: {torch.mm(tensor_A, tensor_B.T)}")
print(f"Output shape: {torch.mm(tensor_A, tensor_B.T).shape}") # torch.mm is the same as torch.matmul


Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output: tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
Output shape: torch.Size([3, 3])


### Finding the min, max, mean, sum, etc (tensor aggregation)

In [56]:
# Create a tensor - note: torch.mean() requires a tensor of float32 datatype
x = torch.arange(0,100,10, dtype=torch.float32)
print(f"tensor is: {x}")
print(f"min value is: {torch.min(x)} or {x.min()}")
print(f"max value is: {torch.max(x)} or {x.max()}")
print(f"mean value is: {torch.mean(x)} or {x.mean()}")
print(f"sum value is: {torch.sum(x)} or {x.sum()}")

tensor is: tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])
min value is: 0.0 or 0.0
max value is: 90.0 or 90.0
mean value is: 45.0 or 45.0
sum value is: 450.0 or 450.0


### Finding the positional min and max

In [57]:
# Find the position in tensor that has the minimum value with argmin() -> returns the index
x.argmin()

tensor(0)

In [63]:
# Find the position in tensor that has the maximum value with argmin() -> returns the index
x.argmax()

tensor(9)

### Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshaps an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeez - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a taregt tensor
* Permute - return a view of the input with dimensions permuted(swapped) in a certain way

In [76]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [77]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [78]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [79]:
# Changing z changes x (because a view of a tensor shares the same memory as the original tensor)
z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [84]:
# Stack tensors on to of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [91]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [92]:
# torch.unsqueeze() - adds a single dimension to a targe tensor at a specific dim (dimension)
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [94]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, color_channels]

# permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [color_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


### Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [96]:
# Creating a tensor
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [97]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [99]:
# Let's index on the middle bracket (dim=1)
print(x[0][0])
print(x[0,0])

tensor([1, 2, 3])
tensor([1, 2, 3])


In [105]:
#LLet's index on the most inner bracket (last dimension)
x[0][0][1]

tensor(2)

In [103]:
x[:,0]

tensor([[1, 2, 3]])

In [104]:
x[:,:,1]

tensor([[2, 5, 8]])

In [106]:
x[:,1,1]

tensor([5])