In [9]:
import torch as T

In [2]:
z = T.zeros(5,3)
print(z)
print(z.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32


All tensors are default as float32 type, if you want to change, use as below

In [5]:
i = T.ones((5,3), dtype=T.int16)
print(i)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


Showing the seeding functionality

In [8]:
T.manual_seed(980579)
r1 = T.rand(2,2)
print(f'A random tensor: {r1}')

r2 = T.rand(2,2)
print(f'A random tensor: {r2}')

T.manual_seed(980579)
r3 = T.rand(2,2)
print(f'A random tensor which should match r1: {r3} ')


A random tensor: tensor([[0.2211, 0.4666],
        [0.9583, 0.4394]])
A random tensor: tensor([[0.6632, 0.7253],
        [0.1091, 0.4544]])
A random tensor: tensor([[0.2211, 0.4666],
        [0.9583, 0.4394]]), which should match r1


In [11]:
ones = T.ones(2,3)
print(ones)

twos = T.ones(2,3) * 3
print(twos)

threes = ones + twos
print(threes)
print(threes.shape)

r1 = T.rand(2,3)
r2 = T.rand(2,3)
r3 = r1 + r2 



tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[3., 3., 3.],
        [3., 3., 3.]])
tensor([[4., 4., 4.],
        [4., 4., 4.]])
torch.Size([2, 3])


Simple Model

In [12]:
import torch.nn as nn # for torch.nn.Module, the parent object for PyTorch models
import torch.nn.functional as F # for the activation function

In [ ]:
class LeNet(nn.Module):
    def __init__(self):
        super(LeNet, self).__init__()

        self.conv1 = nn.Conv2d(1,6,3)
        self.conv2 = nn.Conv2d(6,16,3)

        self.fc1 = nn.Linear(16 * 6 * 6, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    
    def forward(self, x):
        x = F.max_pool2d(F.relu(self.conv1(x)), (2,2))
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)

        return x
    
    def num_flat_features(self, x):
        size = x.size()[1:]
        num_features = 1
        for s in size:
            num_features *= s
        return num_features